StarPeaceAdminHub/Controllers/ManagePackagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DDD.ApplicationLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarPeaceAdminHub.Commands;
using StarPeaceAdminHub.Models;
using StarPeaceAdminHub.Models.Packages;
using StarPeaceAdminHub.Queries;
using StarPeaceAdminHubDomain.IRepositories;

namespace StarPeaceAdminHub.Controllers
{
    //[Authorize(Roles= "Admins")]
    public class ManagePackagesController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index([FromServices] IPackagesListQuery query)
        {
            var results = await query.GetAllPackages();
            var vm = new PackagesListViewModel { Items = results };
            return View(vm);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View("Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Create(
            PackageFullEditViewModel vm,
            [FromServices] ICommandHandler<CreatePackageCommand> command)
        {
            if (ModelState.IsValid) { 
                await command.HandleAsync(new CreatePackageCommand(vm));
                return RedirectToAction(
                    nameof(ManagePackagesController.Index));
            }
            else
                return View("Edit", vm);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(
            int id,
            [FromServices] IPackageRepository repo)
        {
            if (id == 0) return RedirectToAction(
                nameof(ManagePackagesController.Index));
            var aggregate = await repo.Get(id);
            if (aggregate == null) return RedirectToAction(
                nameof(ManagePackagesController.Index));
            var vm = new PackageFullEditViewModel(aggregate);
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(
            PackageFullEditViewModel vm,
            [FromServices] ICommandHandler<UpdatePackageCommand> command)
        {
            if (ModelState.IsValid)
            {
                await command.HandleAsync(new UpdatePackageCommand(vm));
                return RedirectToAction(
                    nameof(ManagePackagesController.Index));
            }
            else
                return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(
            int id,
            [FromServices] ICommandHandler<DeletePackageCommand> command)
        {
            if (id>0)
            {
                await command.HandleAsync(new DeletePackageCommand(id));
                
            }
            return RedirectToAction(
                    nameof(ManagePackagesController.Index));
        }
    }
}

StarPeaceAdminHub/Views/ManagePackages/Edit.cshtml
@model StarPeaceAdminHub.Models.Packages.PackageFullEditViewModel
@inject StarPeaceAdminHub.Queries.IDestinationListQuery destinationsQuery
@{
    ViewData["Title"] = "Edit/Create package";
    var allDestinations = await destinationsQuery.AllDestinations();
}
<div class="container">
    <h2>@ViewData["Title"]</h2>
            <section>
                <form method="post">
                    <hr />
                    <div asp-validation-summary="All" class="text-danger"></div>
                    @if (Model == null)
                    {
                        <input type="hidden" asp-for="Id" value="0" />
                    }
                    else
                    {
                        <input type="hidden" asp-for="Id"  />
                    }
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label asp-for="Name"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-group col-sm-6">
                            <label asp-for="DestinationId"></label>
                            <select asp-for="DestinationId" asp-items="allDestinations" class="form-control">
                                <option value="">select destination</option>
                            </select>
                            <span asp-validation-for="DestinationId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label asp-for="DurationInDays"></label>
                            <input type="number" asp-for="DurationInDays" class="form-control" />
                            <span asp-validation-for="DurationInDays" class="text-danger"></span>
                        </div>

                        <div class="form-group col-sm-6">
                            <label asp-for="Price"></label>
                            <input type="number"  asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label asp-for="StartValidityDate"></label>
                            <input type="date" asp-for="StartValidityDate" class="form-control" />
                            <span asp-validation-for="StartValidityDate" class="text-danger"></span>
                        </div>

                        <div class="form-group col-sm-6">
                            <label asp-for="EndValidityDate"></label>
                            <input type="date"  asp-for="EndValidityDate" class="form-control" />
                            <span asp-validation-for="EndValidityDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-12">
                            <label asp-for="Description"></label>
                            <textarea rows="4" asp-for="Description" class="form-control" >
                            </textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>              
            </section>  
        </div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

StarPeaceAdminHub/Views/ManagePackages/Index.cshtml
@model  StarPeaceAdminHub.Models.Packages.PackagesListViewModel
@using StarPeaceAdminHub.Controllers
@{
    ViewData["Title"] = "Manage packages";
}

    <div class="container">
        <h2>@ViewData["Title"]</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Delete</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Destination</th>
                        <th scope="col">Name</th>
                        <th scope="col">Duration/days</th>
                        <th scope="col">Price</th>
                        <th scope="col">Availble from</th>
                        <th scope="col">Availble to</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach(var package in Model.Items)
                    {
                    <tr>
                        <td>
                            <a asp-controller="ManagePackages"
                               asp-action="@nameof(ManagePackagesController.Delete)"
                               asp-route-id="@package.Id">
                                delete
                            </a>
                        </td>
                        <td>
                            <a asp-controller="ManagePackages"
                               asp-action="@nameof(ManagePackagesController.Edit)"
                               asp-route-id="@package.Id">
                                edit
                            </a>
                        </td>
                        <td>
                            @package.DestinationName
                        </td>
                        <td>
                            @package.Name
                        </td>
                        <td>
                            @package.DurationInDays
                        </td>
                        <td>
                            @package.Price
                        </td>
                        <td>
                            @(package.StartValidityDate.HasValue ?
                                package.StartValidityDate.Value.ToString("d")
                                :
                                String.Empty)
                        </td>
                        <td>
                            @(package.EndValidityDate.HasValue ?
                                package.EndValidityDate.Value.ToString("d")
                                :
                                String.Empty)
                        </td>

                    </tr>

                    }
                </tbody>
            </table>
        </div>
        <a class="btn btn-primary" asp-controller="ManagePackages"
              asp-action="@nameof(ManagePackagesController.Create)">
            New package
        </a>
    </div>