StarPeace.Admin/Controllers/StructuralController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StarPeace.Admin.Models;
using StarPeace.Admin.Helpers;
using StarPeace.Admin.Services;
using StarPeace.Admin.Entities;

namespace StarPeace.Admin.Controllers
{
    public class StructuralController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }   

        public IActionResult FlyWeight()
        {
            return View();
        }  
        // Facade
        public IActionResult Search(string isbn)
        {
            PriceComparer comparer = new PriceComparer();
            List<Book> books = comparer.Compare(isbn);
            return View("Results",books);
        } 

        // Proxy
        [HttpPost]
        public IActionResult ShowStats(string host)
        {
            WebsiteStatsFactory factory = new WebsiteStatsFactory();
            WebsiteStats stats = (WebsiteStats)factory[host];
            if (stats == null)
            {
                ViewBag.Message = "Invalid Host Name!";
                return View("Index");
            }
            else
            {
                return View(stats);
            }
        } 
    }
}

StarPeace.Admin/Views/Structural/Facade.cshtml
@{
    ViewData["Title"] = "Facade Pattern";
}


<html>
<head>
    <title></title>
</head>
<body>
    <h1>Facade Patten</h1>
    
</body>
</html>

StarPeace.Admin/Views/Structural/Flyweight.cshtml
<html>
<head>
    <title></title>
</head>
<body>

    <h1>Enter Host Name :</h1>
    <form asp-controller="Home" asp-action="ShowStats" method="post">
        <input type="text" name="host" />
        <input type="submit" value="Submit" />
    </form>
    <br />
    <strong>@ViewBag.Message</strong>

</body>
</html>

StarPeace.Admin/Views/Structural/Index.cshtml
@{
    ViewData["Title"] = "Structural Patterns";
}
@model StarPeace.Admin.Models.IncomeDetails

<html>
<head>
    <title></title>
</head>
<body>
    <h1>Structural Pattens</h1>
    <div>
         <ul>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Index">Adapter</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Index">Bridge</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Index">Composite</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Index">Decorator</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Facade_Search">Facade</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Index">Flyweight</a>
            </li>
            <li>
                <a asp-area="" asp-controller="Structural" asp-action="Index">Proxy</a>
            </li>       

         </ul>
        <div>
</body>
</html>

StarPeace.Admin/Views/Structural/ShowStats.cshtml
@model StarPeace.Admin.Entities.WebsiteStats

<html>
<head>
    <title>Website Stats</title>
</head>
<body>
    <h1>Usage Stats for @Model.Host</h1>
    <table border="1" cellpadding="10">
        <tr>
            <td>No. of Page Views : </td>
            <td>@Model.PageViews</td>
        </tr>
        <tr>
            <td>No. of Site Visits : </td>
            <td>@Model.SiteVisits</td>
        </tr>
        <tr>
            <td>Total Bandwidth : </td>
            <td>@Model.Bandwidth KB</td>
        </tr>
        <tr>
            <td>Top Search Keywords : </td>
            <td>@Model.TopKeywords</td>
        </tr>
    </table>
</body>
</html>