StarPeaceAdminHub/Controllers/ManageBooksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DDD.ApplicationLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarPeaceAdminHub.Commands;
using StarPeaceAdminHub.Models;
using StarPeaceAdminHub.Models.Categorys;
using StarPeaceAdminHub.Queries;
using StarPeaceAdminHubDomain.IRepositories;

namespace StarPeaceAdminHub.Controllers
{
    [Authorize(Roles= "Admins")]
    public class ManageBooksController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index([FromServices] ICategorysListQuery query)
        {
            var results = await query.GetAllCategorys();
            var vm = new CategorysListViewModel { Items = results };
            return View(vm);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View("Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Create(
            CategoryFullEditViewModel vm,
            [FromServices] ICommandHandler<CreateCategoryCommand> command)
        {
            if (ModelState.IsValid) { 
                await command.HandleAsync(new CreateCategoryCommand(vm));
                return RedirectToAction(
                    nameof(ManageBooksController.Index));
            }
            else
                return View("Edit", vm);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(
            int id,
            [FromServices] ICategoryRepository repo)
        {
            if (id == 0) return RedirectToAction(
                nameof(ManageBooksController.Index));
            var aggregate = await repo.Get(id);
            if (aggregate == null) return RedirectToAction(
                nameof(ManageBooksController.Index));
            var vm = new CategoryFullEditViewModel(aggregate);
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(
            CategoryFullEditViewModel vm,
            [FromServices] ICommandHandler<UpdateCategoryCommand> command)
        {
            if (ModelState.IsValid)
            {
                await command.HandleAsync(new UpdateCategoryCommand(vm));
                return RedirectToAction(
                    nameof(ManageBooksController.Index));
            }
            else
                return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(
            int id,
            [FromServices] ICommandHandler<DeleteCategoryCommand> command)
        {
            if (id>0)
            {
                await command.HandleAsync(new DeleteCategoryCommand(id));
                
            }
            return RedirectToAction(
                    nameof(ManageBooksController.Index));
        }
    }
}

StarPeaceAdminHub/Controllers/ManageCategorysController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DDD.ApplicationLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarPeaceAdminHub.Commands;
using StarPeaceAdminHub.Models;
using StarPeaceAdminHub.Models.Categorys;
using StarPeaceAdminHub.Queries;
using StarPeaceAdminHubDomain.IRepositories;

namespace StarPeaceAdminHub.Controllers
{
    [Authorize(Roles= "Admins")]
    public class ManageCategorysController : Controller
    {
        // 1. A controller's action method receives one or more ViewModels and performs validation.
        [HttpGet]
        public async Task<IActionResult> Index(
            // 5. A command handler matching the previous command is retrieved via DI in
            // the controller action method (through the[FromServices]
            [FromServices] ICategorysListQuery query)
        {
            var results = await query.GetAllCategorys();
            var vm = new CategorysListViewModel { Items = results };
            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Edit");
        }

        // It has a constructor that accepts an ICategory aggregate. This way, package data is
        // copied into the ViewModel that is used to populate the edit view. It implements the
        // ICategoryFullEditDTO DTO interface defined in the domain layer. This way, it can be
        // directly used to send ICategory updates to the domain layer.
        [HttpPost]
        public async Task<IActionResult> Create(
            CategoryFullEditViewModel vm,
            [FromServices] ICommandHandler<CreateCategoryCommand> command)
        {
            if (ModelState.IsValid) { 
                await command.HandleAsync(new CreateCategoryCommand(vm));
                return RedirectToAction(
                    nameof(ManageCategorysController.Index));
            }
            else
                return View("Edit", vm);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(
            int id,
            [FromServices] ICategoryRepository repo)
        {
            if (id == 0) return RedirectToAction(
                nameof(ManageCategorysController.Index));
            var aggregate = await repo.Get(id);
            if (aggregate == null) return RedirectToAction(
                nameof(ManageCategorysController.Index));
            var vm = new CategoryFullEditViewModel(aggregate);
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(
            CategoryFullEditViewModel vm,
            [FromServices] ICommandHandler<UpdateCategoryCommand> command)
        {
            if (ModelState.IsValid)
            {
                await command.HandleAsync(new UpdateCategoryCommand(vm));
                return RedirectToAction(
                    nameof(ManageCategorysController.Index));
            }
            else
                return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(
            int id,
            [FromServices] ICommandHandler<DeleteCategoryCommand> command)
        {
            if (id>0)
            {
                await command.HandleAsync(new DeleteCategoryCommand(id));
                
            }
            return RedirectToAction(
                    nameof(ManageCategorysController.Index));
        }
    }
}

StarPeaceAdminHub/Views/ManageBooks/Index.cshtml
@model  StarPeaceAdminHub.Models.Categorys.CategorysListViewModel
@using StarPeaceAdminHub.Controllers
@{
    ViewData["Title"] = "Manage Books";
}

    <div class="container">
        <h2>@ViewData["Title"]</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Delete</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Title</th>
                        <th scope="col">ISBN</th>
                        <th scope="col">Duration/days</th>
                        <th scope="col">Retail Price</th>
                        <th scope="col">Availble from</th>
                        <th scope="col">Availble to</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach(var Category in Model.Items)
                    {
                    <tr>
                        <td>
                            <button class="btn btn-primary">
                            <a asp-controller="ManageCategorys"
                               asp-action="@nameof(ManageBooksController.Delete)"
                               asp-route-id="@Category.Id">
                                delete
                            </a>
                            </button>
                        </td>
                        <td>
                            <a asp-controller="ManageCategorys"
                               asp-action="@nameof(ManageBooksController.Edit)"
                               asp-route-id="@Category.Id">
                                edit
                            </a>
                        </td>
                        <td>
                            @Category.CategoryName
                        </td>
                        <td>
                            @* @Category.Name *@
                        </td>
                        <td>
                            @* @Category.DurationInDays *@
                        </td>
                        <td>
                            @* @Category.Price *@
                        </td>
                        <td>
                            @* @(Category.StartValidityDate.HasValue ?
                                Category.StartValidityDate.Value.ToString("d")
                                :
                                String.Empty) *@
                        </td>
                        <td>
                            @* @(Category.EndValidityDate.HasValue ?
                                Category.EndValidityDate.Value.ToString("d")
                                :
                                String.Empty) *@
                        </td>

                    </tr>

                    }
                </tbody>
            </table>
        </div>
        <a class="btn btn-primary" asp-controller="ManageCategorys"
              asp-action="@nameof(ManageBooksController.Create)">
            New Book
        </a>
    </div>